ALTER TABLE latest_prices
  ADD COLUMN IF NOT EXISTS market_price DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS market_price_change_percent DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS liquidity DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS volume_24h DOUBLE PRECISION;
